name: Push and publish version branch

on:
  push:
    branches:
      - 'v**'

jobs:
  build-and-deploy:
    uses: electron/website/.github/workflows/build-and-deploy.yml@main
    with:
      branch: version
    secrets:
      SAS: ${{ secrets.SAS }}
