name: 'Update docs'

on:
  repository_dispatch:
    types: [doc_changes]
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The branch of the commit, usually something like `15-x-y`
        required: true
      sha:
        type: string
        description: The SHA of the `electron/electron` commit
        required: true

permissions: {}

jobs:
  update-docs:
    runs-on: ubuntu-latest
    environment: docs-updater
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.DOCS_UPDATER_GH_APP_CREDS }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4.2.2
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # tag: v4.0.4
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@dc9579d3dfb9c0e7a1f56c194eefcb8e2c9f0da5 # tag: v1.10.3
      - name: Prebuild
        run: |
          yarn pre-build ${{ github.event.client_payload.sha || github.event.inputs.sha }} ${{ github.event.client_payload.branch || github.event.inputs.branch }}
          git add .
      - name: Push changes
        uses: dsanders11/github-app-commit-action@43de6da2f4d927e997c0784c7a0b61bd19ad6aac # v1.5.0
        with:
          message: 'chore: update ref to docs (🤖)'
          token: ${{ steps.generate-token.outputs.token }}
